#!/bin/bash

declare -x ETHERPAD_GITHUB_ENABLED
[[ -z "${ETHERPAD_GITHUB_ENABLED}" ]] && ETHERPAD_GITHUB_ENABLED="false"

declare -x ETHERPAD_GITHUB_APP_ID
[[ -z "${ETHERPAD_GITHUB_APP_ID}" ]] && ETHERPAD_GITHUB_APP_ID=""

declare -x ETHERPAD_GITHUB_APP_SECRET
[[ -z "${ETHERPAD_GITHUB_APP_SECRET}" ]] && ETHERPAD_GITHUB_APP_SECRET=""

declare -x ETHERPAD_GITHUB_ORGANIZATION
[[ -z "${ETHERPAD_GITHUB_ORGANIZATION}" ]] && ETHERPAD_GITHUB_ORGANIZATION=""

declare -x ETHERPAD_GITHUB_TEAM
[[ -z "${ETHERPAD_GITHUB_TEAM}" ]] && ETHERPAD_GITHUB_TEAM=""

declare -x ETHERPAD_GITHUB_USERS
[[ -z "${ETHERPAD_GITHUB_USERS}" ]] && ETHERPAD_GITHUB_USERS=""
