#!/bin/bash

declare -x ETHERPAD_LDAP_ENABLED
[[ -z "${ETHERPAD_LDAP_ENABLED}" ]] && ETHERPAD_LDAP_ENABLED="false"

declare -x ETHERPAD_LDAP_URL
[[ -z "${ETHERPAD_LDAP_URL}" ]] && ETHERPAD_LDAP_URL="ldap://openldap"

declare -x ETHERPAD_LDAP_SEARCH_DN
[[ -z "${ETHERPAD_LDAP_SEARCH_DN}" ]] && ETHERPAD_LDAP_SEARCH_DN=""

declare -x ETHERPAD_LDAP_SEARCH_PASSWORD
[[ -z "${ETHERPAD_LDAP_SEARCH_PASSWORD}" ]] && ETHERPAD_LDAP_SEARCH_PASSWORD=""

declare -x ETHERPAD_LDAP_ACCOUNT_BASE
[[ -z "${ETHERPAD_LDAP_ACCOUNT_BASE}" ]] && ETHERPAD_LDAP_ACCOUNT_BASE="ou=Users,dc=example,dc=com"

declare -x ETHERPAD_LDAP_ACCOUNT_PATTERN
[[ -z "${ETHERPAD_LDAP_ACCOUNT_PATTERN}" ]] && ETHERPAD_LDAP_ACCOUNT_PATTERN="(&(objectClass=*)(uid={{\`{{username}}\`}}))"

declare -x ETHERPAD_LDAP_DISPLAYNAME_ATTRIBUTE
[[ -z "${ETHERPAD_LDAP_DISPLAYNAME_ATTRIBUTE}" ]] && ETHERPAD_LDAP_DISPLAYNAME_ATTRIBUTE="cn"

declare -x ETHERPAD_LDAP_GROUP_SEARCH_BASE
[[ -z "${ETHERPAD_LDAP_GROUP_SEARCH_BASE}" ]] && ETHERPAD_LDAP_GROUP_SEARCH_BASE="ou=Groups,dc=example,dc=com"

declare -x ETHERPAD_LDAP_GROUP_ATTRIBUTE
[[ -z "${ETHERPAD_LDAP_GROUP_ATTRIBUTE}" ]] && ETHERPAD_LDAP_GROUP_ATTRIBUTE="member"

declare -x ETHERPAD_LDAP_GROUP_ATTRIBUTE_IS_DN
[[ -z "${ETHERPAD_LDAP_GROUP_ATTRIBUTE_IS_DN}" ]] && ETHERPAD_LDAP_GROUP_ATTRIBUTE_IS_DN="true"

declare -x ETHERPAD_LDAP_SEARCH_SCOPE
[[ -z "${ETHERPAD_LDAP_SEARCH_SCOPE}" ]] && ETHERPAD_LDAP_SEARCH_SCOPE="sub"

declare -x ETHERPAD_LDAP_GROUP_SEARCH
[[ -z "${ETHERPAD_LDAP_GROUP_SEARCH}" ]] && ETHERPAD_LDAP_GROUP_SEARCH="(&(cn=admin)(objectClass=groupOfNames))"

declare -x ETHERPAD_LDAP_ANONYMOUS_READONLY
[[ -z "${ETHERPAD_LDAP_ANONYMOUS_READONLY}" ]] && ETHERPAD_LDAP_ANONYMOUS_READONLY="false"
