#!/bin/bash
source /usr/bin/entrypoint

if [ -f ./pre ]
then
  source ./pre
fi

if [ -d ./custom.d ]
then
  for FILE in $(find ./custom.d -type f -iname *.sh | sort)
  do
    source ${FILE}
  done
fi

if [ -f ./post ]
then
  source ./post
fi

STARTCMD="node node_modules/ep_etherpad-lite/node/server.js"

pushd /srv/www > /dev/null
  echo "> starting etherpad service"
  exec su-exec etherpad ${STARTCMD}
popd > /dev/null
