---
name: readme

"on":
  push:
    branches:
      - master
    paths:
      - README.md
  workflow_dispatch:

jobs:
  readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Push readme
        uses: actionhippie/pushrm@3be2dcf048c674aef56b79f086e40198c0b4ba3b # v1
        if: github.event_name != 'pull_request'
        with:
          provider: dockerhub
          target: webhippie/etherpad
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          description: Docker image for etherpad
          readme: README.md

      - name: Push readme
        uses: actionhippie/pushrm@3be2dcf048c674aef56b79f086e40198c0b4ba3b # v1
        with:
          provider: quay
          target: quay.io/webhippie/etherpad
          apikey: ${{ secrets.QUAY_APIKEY }}
          readme: README.md

...
